import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import ffmpeg from "fluent-ffmpeg";
import ffmpegPath from "ffmpeg-static";
import { nanoid } from "nanoid";
import type { Scene } from "@prisma/client";
import { localUrlForRender } from "../storage.js";

const systemFfmpegPath = "/usr/bin/ffmpeg";

if (existsSync(systemFfmpegPath)) {
  ffmpeg.setFfmpegPath(systemFfmpegPath);
} else if (ffmpegPath) {
  ffmpeg.setFfmpegPath(ffmpegPath as unknown as string);
}

interface RenderInput {
  projectId: string;
  title: string;
  aspectRatio: string;
  scenes: Scene[];
}

export async function renderVideo(input: RenderInput) {
  const outputDirectory = path.resolve("./renders");
  await mkdir(outputDirectory, { recursive: true });
  const filename = `${input.projectId}-${nanoid(8)}.mp4`;
  const outputPath = path.join(outputDirectory, filename);
  const scriptPath = path.join(outputDirectory, `${input.projectId}-${nanoid(8)}.txt`);

  const scriptText = input.scenes
    .sort((a, b) => a.order - b.order)
    .map((scene, index) => `${index + 1}. ${scene.narration}`)
    .join("\\n\\n");

  await writeFile(scriptPath, `${input.title}\\n\\n${scriptText}`, "utf8");

  const { width, height } = dimensionsFor(input.aspectRatio);
  const duration = input.scenes.reduce((sum, scene) => sum + scene.durationSeconds, 0);
  const title = escapeDrawText(input.title);
  const body = escapeDrawText(input.scenes[0]?.narration ?? "AdBot promotional video");

  await new Promise<void>((resolve, reject) => {
    ffmpeg()
      .input(`color=c=#151827:s=${width}x${height}:d=${duration}`)
      .inputFormat("lavfi")
      .videoFilters([
        `drawtext=text='${title}':fontcolor=white:fontsize=${Math.round(width / 14)}:x=(w-text_w)/2:y=h*0.18`,
        `drawtext=text='${body}':fontcolor=white:fontsize=${Math.round(width / 26)}:x=(w-text_w)/2:y=h*0.52:box=1:boxcolor=black@0.35:boxborderw=20`,
        `drawtext=text='Generated by AdBot MVP':fontcolor=#b8b8ff:fontsize=${Math.round(width / 34)}:x=(w-text_w)/2:y=h*0.88`
      ])
      .outputOptions(["-pix_fmt yuv420p", "-movflags +faststart", "-r 30"])
      .output(outputPath)
      .on("end", () => resolve())
      .on("error", reject)
      .run();
  });

  return {
    outputPath,
    outputUrl: localUrlForRender(filename),
    scriptPath
  };
}

export async function renderSceneClip(input: {
  projectId: string;
  scene: Scene;
  aspectRatio: string;
  mediaUrl?: string;
}) {
  const outputDirectory = path.resolve("./renders");
  await mkdir(outputDirectory, { recursive: true });
  const filename = `${input.projectId}-scene-${input.scene.order + 1}-${nanoid(8)}.mp4`;
  const outputPath = path.join(outputDirectory, filename);
  const { width, height } = dimensionsFor(input.aspectRatio);
  const title = escapeDrawText(input.scene.title);
  const narration = escapeDrawText(input.scene.narration);

  await new Promise<void>((resolve, reject) => {
    const command = ffmpeg()
      .input(`color=c=#151827:s=${width}x${height}:d=${input.scene.durationSeconds}`)
      .inputFormat("lavfi")
      .videoFilters([
        `drawtext=text='${title}':fontcolor=white:fontsize=${Math.round(width / 16)}:x=(w-text_w)/2:y=h*0.18`,
        `drawtext=text='${narration}':fontcolor=white:fontsize=${Math.round(width / 30)}:x=(w-text_w)/2:y=h*0.48:box=1:boxcolor=black@0.35:boxborderw=18`,
        `drawtext=text='Scene ${input.scene.order + 1} / ${input.scene.durationSeconds}s':fontcolor=#b8b8ff:fontsize=${Math.round(width / 38)}:x=(w-text_w)/2:y=h*0.86`
      ])
      .outputOptions(["-pix_fmt yuv420p", "-movflags +faststart", "-r 30"])
      .output(outputPath)
      .on("end", () => resolve())
      .on("error", reject);

    command.run();
  });

  return {
    outputPath,
    outputUrl: localUrlForRender(filename)
  };
}

function dimensionsFor(aspectRatio: string) {
  if (aspectRatio === "16:9") {
    return { width: 1280, height: 720 };
  }
  if (aspectRatio === "1:1") {
    return { width: 1080, height: 1080 };
  }
  return { width: 1080, height: 1920 };
}

function escapeDrawText(value: string) {
  return value.replace(/[':\\\\]/g, "\\\\$&").replace(/\n/g, " ");
}
