import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import path from "node:path";
import ffmpegPath from "ffmpeg-static";
import { nanoid } from "nanoid";
import type { Scene } from "@prisma/client";
import { localUrlForRender } from "../storage.js";

const systemFfmpegPath = "/usr/bin/ffmpeg";
const ffmpegExecutable = existsSync(systemFfmpegPath) ? systemFfmpegPath : (ffmpegPath as unknown as string);

interface RenderInput {
  projectId: string;
  title: string;
  aspectRatio: string;
  scenes: Scene[];
  onLog?: RenderLogger;
}

type RenderLogger = (step: string, message: string, metadata?: Record<string, unknown>) => Promise<void> | void;

export async function renderVideo(input: RenderInput) {
  const outputDirectory = path.resolve("./renders");
  await mkdir(outputDirectory, { recursive: true });
  const filename = `${input.projectId}-${nanoid(8)}.mp4`;
  const outputPath = path.join(outputDirectory, filename);
  const scriptPath = path.join(outputDirectory, `${input.projectId}-${nanoid(8)}.txt`);

  const scriptText = input.scenes
    .sort((a, b) => a.order - b.order)
    .map((scene, index) => `${index + 1}. ${scene.narration}`)
    .join("\\n\\n");

  await writeFile(scriptPath, `${input.title}\\n\\n${scriptText}`, "utf8");

  const { width, height } = dimensionsFor(input.aspectRatio);
  const duration = input.scenes.reduce((sum, scene) => sum + scene.durationSeconds, 0);
  const titlePath = path.join(outputDirectory, `${input.projectId}-${nanoid(8)}-title.txt`);
  const bodyPath = path.join(outputDirectory, `${input.projectId}-${nanoid(8)}-body.txt`);
  await writeFile(titlePath, normalizeOverlayText(input.title, 80), "utf8");
  await writeFile(bodyPath, normalizeOverlayText(input.scenes[0]?.narration ?? "AdBot promotional video", 180), "utf8");

  await runFfmpeg(
    [
      "-f", "lavfi",
      "-i", `color=c=#151827:s=${width}x${height}:d=${duration}`,
      "-t", String(duration),
      "-vf", [
        `drawtext=textfile='${escapeFilterPath(titlePath)}':fontcolor=white:fontsize=${Math.round(width / 14)}:x=(w-text_w)/2:y=h*0.18`,
        `drawtext=textfile='${escapeFilterPath(bodyPath)}':fontcolor=white:fontsize=${Math.round(width / 26)}:x=(w-text_w)/2:y=h*0.52:box=1:boxcolor=black@0.35:boxborderw=20`,
        `drawtext=text='Generated by AdBot MVP':fontcolor=#b8b8ff:fontsize=${Math.round(width / 34)}:x=(w-text_w)/2:y=h*0.88`
      ].join(","),
      "-pix_fmt", "yuv420p",
      "-movflags", "+faststart",
      "-r", "24",
      "-preset", "ultrafast",
      "-crf", "32",
      "-y",
      outputPath
    ],
    90,
    input.onLog
  );

  return {
    outputPath,
    outputUrl: localUrlForRender(filename),
    scriptPath
  };
}

export async function renderSceneClip(input: {
  projectId: string;
  scene: Scene;
  aspectRatio: string;
  mediaUrl?: string;
  onLog?: RenderLogger;
  fallbackLabel?: string;
}) {
  const outputDirectory = path.resolve("./renders");
  await mkdir(outputDirectory, { recursive: true });
  const filename = `${input.projectId}-scene-${input.scene.order + 1}-${nanoid(8)}.mp4`;
  const outputPath = path.join(outputDirectory, filename);
  const { width, height } = dimensionsFor(input.aspectRatio);
  const titlePath = path.join(outputDirectory, `${input.projectId}-scene-${input.scene.order + 1}-${nanoid(8)}-title.txt`);
  const narrationPath = path.join(outputDirectory, `${input.projectId}-scene-${input.scene.order + 1}-${nanoid(8)}-narration.txt`);
  await writeFile(titlePath, normalizeOverlayText(input.scene.title, 80), "utf8");
  await writeFile(narrationPath, normalizeOverlayText(input.scene.narration, 180), "utf8");

  const sceneFilters = [
    input.mediaUrl ? `scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height}` : undefined,
    `drawtext=textfile='${escapeFilterPath(titlePath)}':fontcolor=white:fontsize=${Math.round(width / 16)}:x=(w-text_w)/2:y=h*0.18`,
    `drawtext=textfile='${escapeFilterPath(narrationPath)}':fontcolor=white:fontsize=${Math.round(width / 30)}:x=(w-text_w)/2:y=h*0.48:box=1:boxcolor=black@0.35:boxborderw=18`,
    `drawtext=text='${input.fallbackLabel ?? `Scene ${input.scene.order + 1} / ${input.scene.durationSeconds}s`}':fontcolor=#b8b8ff:fontsize=${Math.round(width / 38)}:x=(w-text_w)/2:y=h*0.86`
  ].filter(Boolean).join(",");

  const mediaArgs = input.mediaUrl
    ? [
        "-stream_loop", "-1",
        "-i", input.mediaUrl,
        "-t", String(input.scene.durationSeconds),
        "-vf", sceneFilters,
        "-an"
      ]
    : [
        "-f", "lavfi",
        "-i", `color=c=#151827:s=${width}x${height}:d=${input.scene.durationSeconds}`,
        "-t", String(input.scene.durationSeconds),
        "-vf", sceneFilters
      ];

  if (input.mediaUrl) {
    await input.onLog?.("scene_media_background_used", "משתמש במדיה שנבחרה כרקע לסצנה", {
      sceneId: input.scene.id,
      mediaUrl: input.mediaUrl
    });
  }

  await runFfmpeg(
    [
      ...mediaArgs,
      "-pix_fmt", "yuv420p",
      "-movflags", "+faststart",
      "-r", "24",
      "-preset", "ultrafast",
      "-crf", "32",
      "-y",
      outputPath
    ],
    input.mediaUrl ? 60 : 35,
    input.onLog
  );

  return {
    outputPath,
    outputUrl: localUrlForRender(filename)
  };
}

export async function mergeSceneClips(input: {
  projectId: string;
  clipPaths: string[];
  onLog?: RenderLogger;
}) {
  const outputDirectory = path.resolve("./renders");
  await mkdir(outputDirectory, { recursive: true });
  const filename = `${input.projectId}-final-${nanoid(8)}.mp4`;
  const outputPath = path.join(outputDirectory, filename);
  const concatListPath = path.join(outputDirectory, `${input.projectId}-concat-${nanoid(8)}.txt`);

  if (input.clipPaths.length === 0) {
    throw new Error("Cannot merge final video because no scene clips were rendered.");
  }

  await writeFile(
    concatListPath,
    input.clipPaths.map((clipPath) => `file '${escapeConcatPath(clipPath)}'`).join("\n"),
    "utf8"
  );

  await runFfmpeg(
    [
      "-f", "concat",
      "-safe", "0",
      "-i", concatListPath,
      "-c", "copy",
      "-movflags", "+faststart",
      "-y",
      outputPath
    ],
    45,
    input.onLog
  );

  return {
    outputPath,
    outputUrl: localUrlForRender(filename)
  };
}

function dimensionsFor(aspectRatio: string) {
  if (aspectRatio === "16:9") {
    return { width: 854, height: 480 };
  }
  if (aspectRatio === "1:1") {
    return { width: 720, height: 720 };
  }
  return { width: 540, height: 960 };
}

function normalizeOverlayText(value: string, maxLength: number) {
  return value
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, maxLength);
}

function escapeFilterPath(value: string) {
  return value.replace(/\\/g, "/").replace(/:/g, "\\:").replace(/'/g, "\\'");
}

function escapeConcatPath(value: string) {
  return value.replace(/\\/g, "/").replace(/'/g, "'\\''");
}

async function runFfmpeg(args: string[], timeoutSeconds: number, onLog?: RenderLogger) {
  await onLog?.("ffmpeg_start", "FFmpeg התחיל לרנדר", {
    executable: ffmpegExecutable,
    timeoutSeconds
  });
  await onLog?.("ffmpeg_command", "פקודת FFmpeg הופעלה", {
    commandLine: `${ffmpegExecutable} ${args.join(" ")}`.slice(0, 800)
  });

  await new Promise<void>((resolve, reject) => {
    const child = spawn(ffmpegExecutable, args, { stdio: ["ignore", "ignore", "pipe"] });
    let stderr = "";
    let lastLogAt = Date.now();
    const timeout = setTimeout(() => {
      child.kill("SIGKILL");
      void onLog?.("ffmpeg_timeout", "FFmpeg עבר timeout ונעצר", { timeoutSeconds, stderr: stderr.slice(-800) });
      reject(new Error(`FFmpeg timed out after ${timeoutSeconds} seconds`));
    }, timeoutSeconds * 1000);

    child.stderr.on("data", (chunk: Buffer) => {
      const text = chunk.toString();
      stderr += text;
      const now = Date.now();
      if (now - lastLogAt > 5000) {
        lastLogAt = now;
        void onLog?.("ffmpeg_progress", "FFmpeg עדיין עובד", { stderrTail: stderr.slice(-500) });
      }
      if (/error|failed|invalid|conversion/i.test(text)) {
        void onLog?.("ffmpeg_stderr", "FFmpeg דיווח אזהרה/שגיאה", { line: text.slice(-500) });
      }
    });

    child.on("error", (error) => {
      clearTimeout(timeout);
      void onLog?.("ffmpeg_error", "לא ניתן להפעיל את FFmpeg", { error: error.message });
      reject(error);
    });

    child.on("close", (code) => {
      clearTimeout(timeout);
      if (code === 0) {
        void onLog?.("ffmpeg_done", "FFmpeg סיים בהצלחה");
        resolve();
        return;
      }

      const message = `FFmpeg exited with code ${code}: ${stderr.slice(-1000)}`;
      void onLog?.("ffmpeg_error", "FFmpeg נכשל", { code, stderr: stderr.slice(-1000) });
      reject(new Error(message));
    });
  });
}
